### ISSUE TITLE
Script Output confirmation

### ISSUE THREAD

**Issue by sadiqaliarsalan** [schnupperkursde/scraper_template#1]
![first](https://user-images.githubusercontent.com/46757772/51631966-f2644800-1f6f-11e9-84a1-b9c11b7dbce9.png)

Hi .. Hope you're doing great. 
I transferred both of the python scripts according to the template provided.
I installed docker etc. and then run the script under the container.

Just to confirm about the output which I got when I run the script under container.
Please let me know if the output is not correct and please guide me how can I run the script if it's not right in the screen shot.

Best
- Arsalan

**Comment by siavash9000** [comment]
Hi Arsalan,

thanks for the screenshot. Everything looks fine, according to the logs everything is fine.

The next steps are now:
* rename the template to a proper filename
* implement your scraper in the ```parse``` method which you find in the template

The results you parse will be saved automatically to an Excel file.

Do not hesitate to ask more questions. Hopes this helps.

Greetings,
Siavash

**Comment by siavash9000** [comment]
Hello Arsalan,
I added recently an example for a scraper based on the template. Maybe it is a help for you.
The file is "example.py".

**Comment by sadiqaliarsalan** [comment]
Hi Siavash

I've already changed both of scripts according to the template you provided (I got both final files in my laptop and want to show you and send you).
can you contact me through Skype Id: arsalanalisadiq
I want to discuss few things and maybe share screen to show you couple of commands.

Best
Arsalan

**Comment by siavash9000** [comment]
Hello Arsalan,

I am happy to hear you had no problems. Unfortunately a Skype Session is not possible. Please discuss all your questions and problems here, since we use the issue function of Github as archive.

If your are finished, please send your script  to Timo.

Thank you very much,
Siavash

**Comment by sadiqaliarsalan** [comment]
no problem. 
I'm sending my scripts to Timo.
Please have a look.

Thank you.

**Comment by siavash9000** [comment]
Hello Arsalan,

thank you. But please do not hesitate to ask anything. We can discuss
results or problems here as well as in Skype.

Thank you,
Siavash

Am Mi., 30. Jan. 2019, 09:52 hat sadiqaliarsalan <notifications@github.com>
geschrieben:

**Comment by sadiqaliarsalan** [comment]
Hi Siavash

I think there is some problem with the template's **save_results(data)** method. I'm passing it a list of lists as required and mentioned in the template file but it's not making .xlsx file correctly.

Here is my resultant list which I'm passing to the **save_results(data)** method in the argument 'date'.
[['Düsseldorf - Schadow Arkaden', 'BodyFit', 'Montag', 'Vormittags', 'Düsseldorf - Schadow Arkaden', '09:00', '09:55', 'Alle Mitglieder', 'https://www.fitnessfirst.de/kurse/toning/bodyweight/bodyfit', 'https://www.fitnessfirst.de/kurse/kursplan?club_id=0092'], ['Düsseldorf - Schadow Arkaden', 'FlexiFit', 'Montag', 'Vormittags', 'Düsseldorf - Schadow Arkaden', '10:00', '11:00', 'Alle Mitglieder', 'https://www.fitnessfirst.de/kurse/health/rueckentraining/flexifit', 'https://www.fitnessfirst.de/kurse/kursplan?club_id=0092'], ['Düsseldorf - Schadow Arkaden', 'BodyFit', 'Montag', 'Nachmittags', 'Düsseldorf - Schadow Arkaden', '09:00', '09:55', 'Alle Mitglieder', 'https://www.fitnessfirst.de/kurse/toning/bodyweight/bodyfit', 'https://www.fitnessfirst.de/kurse/kursplan?club_id=0092'], ['Düsseldorf - Schadow Arkaden', 'FlexiFit', 'Montag', 'Nachmittags', 'Düsseldorf - Schadow Arkaden', '10:00', '11:00', 'Alle Mitglieder', 'https://www.fitnessfirst.de/kurse/health/rueckentraining/flexifit', 'https://www.fitnessfirst.de/kurse/kursplan?club_id=0092'], ['Düsseldorf - Schadow Arkaden', 'BodyFit', 'Montag', 'Abends', 'Düsseldorf - Schadow Arkaden', '09:00', '09:55', 'Alle Mitglieder', 'https://www.fitnessfirst.de/kurse/toning/bodyweight/bodyfit', 'https://www.fitnessfirst.de/kurse/kursplan?club_id=0092'], ['Düsseldorf - Schadow Arkaden', 'FlexiFit', 'Montag', 'Abends', 'Düsseldorf - Schadow Arkaden', '10:00', '11:00', 'Alle Mitglieder', 'https://www.fitnessfirst.de/kurse/health/rueckentraining/flexifit', 'https://www.fitnessfirst.de/kurse/kursplan?club_id=0092']]

But the problem is it's not saving the data correctly.
Here is output screenshot of the data which is saved in .xlsx file.

![result](https://user-images.githubusercontent.com/46757772/51980831-08639280-24b3-11e9-87d1-a9a9f136a49c.png)


Thank you
Arsalan.

**Comment by siavash9000** [comment]
Hello Arsalan, 
you are right. The template had a bug. Please take a look at the updated template file selenium_template.py and change the method save_results in your script. Just copy the method and override it in your script.
Please let me know, if this fixes the Bug for you.
Thanks ,
Siavash

**Comment by sadiqaliarsalan** [comment]
I'm sorry Siavash but I'm having that problem again after even copying the **save_result** method from example.py and updated template file.
I'm not getting the saved data properly into the .xlsx file.

do you want me to fix this bug or you'll do it yourself ?

Thank you.
Arsalan.

**Comment by siavash9000** [comment]
Hello Arsalan,
no problem. We will find the problem. Can you share your script with a gist?
You can create a gist like this https://help.github.com/articles/creating-gists/
Alternatively you can paste it here.
Siavash

**Comment by sadiqaliarsalan** [comment]
Please visit this link below
https://gist.github.com/sadiqaliarsalan/85ef2b6df6884909b6e02aab4a5ed6a0

Thank you.
Arsalan

**Comment by siavash9000** [comment]
Thanks. I will debug it and contact you tomorrow or monday.

**Comment by siavash9000** [comment]
Hello Arsalan,

you are using a file called first.xlsx in the script in line 28:

`workbook_path = str('/root/Desktop/first.xlsx')`

It seems your script depends on this file, so please send me a copy, so that I can debug the script.

Thank you,
Siavash

**Comment by sadiqaliarsalan** [comment]
yeah It's just an excel file with two columns one with name and other with link. i used it for testing the script but the actual file will contain all the names of studio's and their links to scrape the data.
you can use this for testing purpose.

[first.xlsx](https://github.com/schnupperkursde/scraper_template/files/2825493/first.xlsx)

Thank you
Arsalan.

**Comment by siavash9000** [comment]
Hello Arsalan, 
thank you. The script runs. I close this issue now.
